### ISSUE TITLE
Semaphore extension

### ISSUE THREAD

**Issue by sumachaa** [typhonius/acquia_cli#24]
getting the below error when using this, please let me know how we can address this

```
+ vendor/bin/acquiacli app:list
PHP Warning:  Declaration of AcquiaCli\Commands\AcquiaCommand::confirm($question) should be compatible with Robo\Tasks::confirm($question, $default = false) in /vendor/typhonius/acquia_cli/src/Commands/AcquiaCommand.php on line 19
PHP Fatal error:  Uncaught Symfony\Component\Lock\Exception\InvalidArgumentException: Semaphore extension (sysvsem) is required in /vendor/symfony/lock/Store/SemaphoreStore.php:41
Stack trace:
#0 /vendor/typhonius/acquia_cli/src/AcquiaCli.php(88): Symfony\Component\Lock\Store\SemaphoreStore->__construct()
#1 /vendor/typhonius/acquia_cli/bin/acquiacli-robo.php(44): AcquiaCli\AcquiaCli->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /vendor/typhonius/acquia_cli/bin/acquiacli(11): require_once('/home/jenkins/w...')
#3 {min}
  ​thrown in /vendor/symfony/lock/Store/SemaphoreStore.php on line 41
```

**Comment by heddn** [comment]
Confirmed. Getting this as well on a fresh install. PHP 7.2

**Comment by typhonius** [comment]
Thanks for the PR, I've merged it in.

**Comment by shelane** [comment]
That fixes only the warning. I still get this:
```
./vendor/bin/acquiacli setup

Fatal error: Uncaught Symfony\Component\Lock\Exception\InvalidArgumentException: Semaphore extension (sysvsem) is required in /var/www/vendor/symfony/lock/Store/SemaphoreStore.php:40
Stack trace:
#0 /var/www/vendor/typhonius/acquia_cli/src/AcquiaCli.php(88): Symfony\Component\Lock\Store\SemaphoreStore->__construct()
#1 /var/www/vendor/typhonius/acquia_cli/bin/acquiacli-robo.php(44): AcquiaCli\AcquiaCli->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/vendor/typhonius/acquia_cli/bin/acquiacli(11): require_once('/var/www/vendor...')
#3 {main}
  thrown in /var/www/vendor/symfony/lock/Store/SemaphoreStore.php on line 40
```

**Comment by typhonius** [comment]
@shelane thanks for that. I wonder if this is similar to the issue the folks are seeing over here: https://github.com/contao/contao/issues/337

Is it possible your local PHP wasn’t compiled with sysvsem?

**Comment by shelane** [comment]
I'm using the Docksal php 7.3 image
https://github.com/docksal/service-cli/blob/develop/7.3/Dockerfile

It does not look like it is.

**Comment by typhonius** [comment]
If they’re unable to add, we could look at using FlockStore instead of SemaphoreStore as that uses the file system rather than PHP. 

I’ll keep this issue closed, if you hear back from docksal and still need support here, could I ask you to open a new issue and we’ll track it there.
